#!/bin/bash - 

#===============================================================================
#
#          FILE: vimrc
#         USAGE: vimrc {bash|c|help}
#   DESCRIPTION: Apply ~/.vimrc configurations in real-time. 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Kostya Zolotarov, <kostya.zolotarov@gmail.com>
#       CREATED: 2020-11-15 14:39
#      REVISION: ---
#
#===============================================================================
#
# The MIT License (MIT)
#
# Copyright (c) 2020, Kostya Zolotarov
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do
# so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
#===============================================================================

#---  FUNCTION  ----------------------------------------------------------------
#          NAME:  install_bash_configuration
#   DESCRIPTION:  Install and reload Bash configuration of ~/.vimrc. 
#    PARAMETERS:  None 
#       RETURNS:  Bash exit status 
#-------------------------------------------------------------------------------
install_bash_configuration() 
{
    echo "Installing Bash configuration to ~/.vimrc ..."
    rm ~/.vimrc
    ln -s ~/Sources/settings/src/vim/vimrc-bash ~/.vimrc
}

#---  FUNCTION  ----------------------------------------------------------------
#          NAME:  install_c_configuration
#   DESCRIPTION:  Install and reload C configuration of ~/.vimrc.  
#    PARAMETERS:  None 
#       RETURNS:  Bash exit status 
#-------------------------------------------------------------------------------
install_c_configuration() 
{
    echo "Installing C configuration to ~/.vimrc ..."
    rm ~/.vimrc
    ln -s ~/Sources/settings/src/vim/vimrc-c ~/.vimrc
}

#---  FUNCTION  ----------------------------------------------------------------
#          NAME:  show_usage
#   DESCRIPTION:  Display application usage options and version. 
#    PARAMETERS:  None 
#       RETURNS:  Bash exit status 
#-------------------------------------------------------------------------------
show_usage() 
{
    echo $"Usage: "${0##*/}" {bash|c|help}"
}

case "$1" in 

    bash)
        install_bash_configuration
        ;;

    c)
        install_c_configuration
        ;;

    *)
        show_usage 
        ;;

esac 

#===============================================================================
